require 'open-uri'
require 'net/http'
require 'json'
require 'tty-prompt'
require 'uri-handler'
require 'hirb'
require 'colorize'

require_relative 'strain.rb'
require_relative 'strain_importer.rb'
require_relative 'Strainz.rb'