
require 'open-uri'
require 'net/http'
require 'json'
require 'tty-prompt'
require 'uri-handler'
require 'hirb'
require 'colorize'
require_relative '../lib/strain.rb/'
require_relative '../lib/strain_importer.rb'
require_relative '../lib/Strainz.rb'